### 1. Test Đăng ký (Tự động tạo UUID và Avatar mặc định)
POST http://localhost:8081/api/auth/register
Content-Type: application/json

{
  "username": "phat_uit_v2",
  "password": "matkhau123"
}

### 2. Test Đăng nhập (Lấy Access Token & Refresh Token)
POST http://localhost:8081/api/auth/login
Content-Type: application/json

{
  "username": "phat_uit_v2",
  "password": "matkhau123"
}

### 3. Test lấy Profile (Dành cho ông bạn A gọi sang)
# QUAN TRỌNG:
# 1. Thay thế <ĐIỀN_USER_ID_VÀO_ĐÂY> bằng cái userId lấy được ở bước 2
# 2. Thay thế <ĐIỀN_ACCESS_TOKEN_VÀO_ĐÂY> bằng chuỗi accessToken lấy được ở bước 2
GET http://localhost:8081/api/users/profile/28886e3d-e933-4a2a-803f-f3a546a204fe
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwaGF0X3VpdF92MiIsInVzZXJJZCI6IjI4ODg2ZTNkLWU5MzMtNGEyYS04MDNmLWYzYTU0NmEyMDRmZSIsInJvbGUiOiJNRU1CRVIiLCJpYXQiOjE3Nzg3NzU3MDcsImV4cCI6MTc3ODc4MjkwN30.bIY4o7gGHBlgpS_nam9V_q9v6xq1tu9u9ZSXaixBGMc

### 4. Test Đổi Refresh Token lấy Access Token mới
POST http://localhost:8081/api/auth/refresh
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwaGF0X3VpdF92MiIsImlhdCI6MTc3ODc3NTcwNywiZXhwIjoxNzc5MzgwNTA3fQ.oEAt5fsHgQpA6zxBQAOehfvJXjFquDfYeN8aRndCD6Q"
}
### 5. Test Cập nhật Profile (Đổi Avatar, Bio, Tên hiển thị)
# Nhớ thay <USER_ID> và <ACCESS_TOKEN> giống như lúc test lấy Profile nhé
PUT http://localhost:8081/api/users/28886e3d-e933-4a2a-803f-f3a546a204fe/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwaGF0X3VpdF92MiIsInVzZXJJZCI6IjI4ODg2ZTNkLWU5MzMtNGEyYS04MDNmLWYzYTU0NmEyMDRmZSIsInJvbGUiOiJNRU1CRVIiLCJpYXQiOjE3Nzg3NzU3MDcsImV4cCI6MTc3ODc4MjkwN30.bIY4o7gGHBlgpS_nam9V_q9v6xq1tu9u9ZSXaixBGMc
Content-Type: application/json

{
  "displayName": "Phát SE",
  "avatarUrl": "https://imgur.com/avatar-moi-cuc-ngau.png",
  "bio": "Sinh viên Kỹ thuật phần mềm UIT, chúa tể fix bug, kẻ hủy diệt deadline."
}

### 6. Test Đổi mật khẩu
PUT http://localhost:8081/api/users/28886e3d-e933-4a2a-803f-f3a546a204fe/password
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwaGF0X3VpdF92MiIsInVzZXJJZCI6IjI4ODg2ZTNkLWU5MzMtNGEyYS04MDNmLWYzYTU0NmEyMDRmZSIsInJvbGUiOiJNRU1CRVIiLCJpYXQiOjE3Nzg3NzU3MDcsImV4cCI6MTc3ODc4MjkwN30.bIY4o7gGHBlgpS_nam9V_q9v6xq1tu9u9ZSXaixBGMc
Content-Type: application/json

{
  "oldPassword": "matkhau123",
  "newPassword": "matkhaumoi456"
}

### 7. Test Đổi Quyền (Thăng cấp lên ADMIN)
PUT http://localhost:8081/api/users/28886e3d-e933-4a2a-803f-f3a546a204fe/role
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwaGF0X3VpdF92MiIsInVzZXJJZCI6IjI4ODg2ZTNkLWU5MzMtNGEyYS04MDNmLWYzYTU0NmEyMDRmZSIsInJvbGUiOiJNRU1CRVIiLCJpYXQiOjE3Nzg3NzU3MDcsImV4cCI6MTc3ODc4MjkwN30.bIY4o7gGHBlgpS_nam9V_q9v6xq1tu9u9ZSXaixBGMc
Content-Type: application/json

{
  "role": "ADMIN"
}

### 8. Test BAN NICK (Khóa tài khoản)
PUT http://localhost:8081/api/users/28886e3d-e933-4a2a-803f-f3a546a204fe/role
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwaGF0X3VpdF92MiIsInVzZXJJZCI6IjI4ODg2ZTNkLWU5MzMtNGEyYS04MDNmLWYzYTU0NmEyMDRmZSIsInJvbGUiOiJNRU1CRVIiLCJpYXQiOjE3Nzg3NzU3MDcsImV4cCI6MTc3ODc4MjkwN30.bIY4o7gGHBlgpS_nam9V_q9v6xq1tu9u9ZSXaixBGMc
Content-Type: application/json

{
  "role": "BANNED"
}