server:
  port: 8085

spring:
  application:
    name: server-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/chat_server_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: ${MYSQL_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true